Algoritmo "volume_paralelípípedo"
// Descrição   :cálculo do do volume do paralelípípedo
// Autor(a)    : João Fernandes
// Data atual  : 21/09/2017
Var
comprimento,volume,largura,altura: real
Inicio
escreva("Qual é o comprimento?")
leia(comprimento)
escreva("Qual é a largura?")
leia(largura)
escreva("Qual é a altura?")
leia(altura)
volume<-comprimento*altura*largura
escreva("O volume é ",volume)
Fimalgoritmo