Algoritmo "Área do trapézio"
// Descrição   :cálculo da área do trapézio
// Autor(a)    : João Fernandes
// Data atual  : 21/09/2017
Var
 basemaior,basemenor,altura,area: real
Inicio
escreva("Qual é a base maior?")
leia(basemaior)
escreva("Qual é a base menor?")
leia(basemenor)
escreva("Qual é a altura?")
leia(altura)
Area<-(basemaior+basemenor)*altura/2
escreva("A área é ",area)
Fimalgoritmo